version: '3.9'

services:
    localstack:
        image: localstack/localstack:latest
        container_name: localstack
        ports:
            - '4566-4597:4566-4597'
        environment: 
          - AWS_DEFAULT_REGION=us-east-1
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

networks:
    default:
        name: localstack
        



# version: '3.0'

# services:
#   localstack:
#     image: localstack/localstack:latest
#     environment: 
#       - AWS_DEFAULT_REGION=us-east-1
#       - EDGE_PORT=4566
#       - SERVICES=sqs,sns
#     ports:
#       - '4566-4597:4566-4597'
#     volumes:
#       - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
#       - "/var/run/docker.sock:/var/run/docker.sock"