version: '2.1'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4576:4576"
      - "8080:8080"
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - SERVICES=sqs,sns,lambda